### ISSUE TITLE
CLI, please!

### ISSUE THREAD

**Issue by aantonov-runbuggy** [jonathanstowe/Acme-Insult-Lala#2]
Please provide a CLI interface to the functionalities. For example:

```shell
generate-insult -n=3
```

```
jaded ill-breeding giglet
clouted toad-spotted skainsmate
goatish crook-pated remnant
```

-----

P.S. Please note the that title of this issue is not something, like, "where is the CLI, you quailing dizzy-eyed pantaloon!"

**Comment by jonathanstowe** [comment]
That seems eminently doable, let me have a look.

**Comment by jonathanstowe** [comment]
There the greasy beetle-headed remnant of a release should be winging its way to a zef repo near you as I type.

**Comment by antononcube** [comment]
Thank you!
